package egolf6;

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
//
//                    Source Code Generated by
//                           CA Gen 8.6
//
//      TARGET OS:  JVM                DBMS:  JDBC            
//
//      ACCESS METHOD:  JDBC                //
//        Name:  DELETE-SCORING_RECORD//
//      UserID:   mansour//
//        Date:  2017  Time:  22:14:54//
//    Copyright (c) 2017 CA Technologies. All rights reserved.//
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// Import Statements
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 
import java.lang.*;
import java.io.*;
import java.util.*;
import java.sql.*;
import java.math.*;
import com.ca.gen.vwrt.*;
import com.ca.gen.vwrt.types.*;
import com.ca.gen.abrt.*;
import com.ca.gen.abrt.functions.*;
import com.ca.gen.abrt.cascade.*;
import com.ca.gen.abrt.trace.*;
import com.ca.gen.exits.common.*;
 
public class E0001035 extends ABBase
{
  // internal flag used for delete/disassociate td action block
  String dl_0118489143;
  int relmm_cgvalue;
  DAQueue pdaQueueCMCB;
  // * * * * * * * * * * * * * * * * * * *
  // HOST VARIABLES FOR TABLE: SCORING_RECORD
  // * * * * * * * * * * * * * * * * * * *
  java.sql.Date date0_003EF;
  java.sql.Time time0_007EF;
  String fk_golferuserid_027EF;
  String fk_scoring_recofk_golferuserid_037EF;
  java.sql.Time fk_scoring_recotime0_041EF;
  java.sql.Date fk_scoring_recodate0_045EF;
  
  // * * * * * * * * * * * * * * * * * * *
  // VIEW FOR TABLE: SCORING_RECORD
  // * * * * * * * * * * * * * * * * * * *
  java.sql.Date date0_005EF;
  java.sql.Time time0_009EF;
  String fk_golferuserid_029EF;
  
  // * * * * * * * * * * * * * * * * * * *
  // VIEW FOR TABLE: SCORE_CARD
  // * * * * * * * * * * * * * * * * * * *
  String fk_scoring_recofk_golferuserid_039EF;
  java.sql.Time fk_scoring_recotime0_043EF;
  java.sql.Date fk_scoring_recodate0_047EF;
  
  // * * * * * * * * * * * * * * * * * * *
  // VIEW FOR TABLE: GOLFER
  // * * * * * * * * * * * * * * * * * * *
  String userid_053EF;
  
  PreparedStatement hstmt_0053477378_1;
  ResultSet hstmt_0053477378_1_rs;
  int hstmt_0053477378_1_cnt;
  
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // MISC DECLARATIONS AND PROTOTYPES 
  //    FOLLOW AS NEEDED:             
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  PreparedStatement hstmt_0118489143_1;
  ResultSet hstmt_0118489143_1_rs;
  int hstmt_0118489143_1_cnt;
  
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  //  CONSTRUCTOR FOR THE CLASS       
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  public E0001035()
  {
    iefCGenRlse = "CA Gen 8.6";
    ssCopyright = "Copyright (c) 2017 CA Technologies. All rights reserved.";
    iefCGenDate = "2017/07/17";
    iefCGenTime = "22:14:54";
    iefCGenEncy = "9.2.A6";
    iefCGenUserId = "mansour";
    iefCGenModel = "EGOLF";
    iefCGenSubset = "ALL";
    iefCGenName = "E0001035";
  }
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // FUNCTION DECLARATIONS 
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  
  
  
  public static void E0001035(Object in_runtime_parm1, IRuntimePStepContext in_runtime_parm2, GlobData in_globdata, DAQueue 
    in_pdaQueueCMCB, int in_relmm_cgvalue, java.sql.Date parm_date0_005EF, java.sql.Time parm_time0_009EF, String 
    parm_fk_golferuserid_029EF)
  {
    E0001035 obj = new E0001035();
    obj.iefRuntimeParm1 = in_runtime_parm1;
    obj.iefRuntimeParm2 = in_runtime_parm2;
    obj.globdata = in_globdata;
    obj.pdaQueueCMCB = in_pdaQueueCMCB;
    obj.relmm_cgvalue = in_relmm_cgvalue;
    obj.date0_005EF = parm_date0_005EF;
    obj.time0_009EF = parm_time0_009EF;
    obj.fk_golferuserid_029EF = parm_fk_golferuserid_029EF;
    obj.mainE0001035();
  }
  
  public void mainE0001035()
  {
    try {
      
      globdata.getStateData().setCurrentABId( "0118489143" );
      
      globdata.getStateData().setCurrentABName( "DELETE-SCORING_RECORD" );
      
      dl_0118489143 = ErrorData.SUCCEEDS_FL_LS;
      
      f_118489143_restrict();
      f_118489143_delete();
      f_118489143_evaluate();
    } catch( ABException e ) {
    }
  }
  
  
  public void f_118489143_evaluate()
  	throws ABException
  {
    f_0118489143_evaluate_exit: 
    {
      if ( relmm_cgvalue == 0 )
      {
        f_4085();
        f_1039();
        break f_0118489143_evaluate_exit;
      }
      if ( relmm_cgvalue == 4085 )
      {
        f_1039();
        break f_0118489143_evaluate_exit;
      }
      if ( relmm_cgvalue == 1039 )
      {
        f_4085();
        break f_0118489143_evaluate_exit;
      }
      throw new ABException();
    }
  }
  
  
  public void f_118489143_restrict()
  	throws ABException
  {
    f_0118489143_restrict_exit: 
    {
      if ( relmm_cgvalue == 0 )
      {
        f_4085_restrict();
        break f_0118489143_restrict_exit;
      }
      if ( relmm_cgvalue == 1039 )
      {
        f_4085_restrict();
        break f_0118489143_restrict_exit;
      }
    }
  }
  
  
  //   DELETE SCORING_RECORD
  public void f_118489143_delete()
  	throws ABException
  {
    date0_003EF = date0_005EF;
    time0_007EF = time0_009EF;
    fk_golferuserid_027EF = fk_golferuserid_029EF;
    sqlException = null;
    try {
      if ( hstmt_0118489143_1 == null )
      {
        SQLStatement.setLength(0);
        
        SQLStatement.append("DELETE FROM ");
        SQLStatement.append("`SCORING_RECORD`");
        SQLStatement.append(" WHERE ");
        SQLStatement.append("`DATE0` = ?");
        SQLStatement.append(" AND `TIME0` = ?");
        SQLStatement.append(" AND `FK_GOLFERUSERID` = ?");
        hstmt_0118489143_1 = globdata.getDBMSData().getDBMSManager().getStatement(globdata, iefRuntimeParm2, "golfer1", 
          SQLStatement.toString());
      }
      hstmt_0118489143_1.setDate(1, date0_003EF);
      hstmt_0118489143_1.setTime(2, time0_007EF);
      globdata.getDBMSData().getDBMSManager().bindParameterString("golfer1", hstmt_0118489143_1, 3, fk_golferuserid_027EF);
      hstmt_0118489143_1.execute();
      hstmt_0118489143_1_rs = hstmt_0118489143_1.getResultSet();
      hstmt_0118489143_1_cnt = hstmt_0118489143_1.getUpdateCount();
    } catch( SQLException e ) {
      sqlException = e;
    }
    if ( ((globdata.getDBMSData().getDBMSManager().wasNoDataFound(sqlException)) || ((globdata.getDBMSData().getDBMSManager()
      .wasSuccessful(sqlException) && (hstmt_0118489143_1_cnt == 0 || hstmt_0118489143_1_cnt == -1)))) || ((globdata.getDBMSData()
      .getDBMSManager().wasSuccessful(sqlException) && hstmt_0118489143_1_cnt == 1)) )
    {
      try {
        if ( hstmt_0118489143_1_rs != null )
        {
          hstmt_0118489143_1_rs.close();
          hstmt_0118489143_1_rs = null;
        }
        if ( hstmt_0118489143_1 != null )
        {
          hstmt_0118489143_1.close();
          hstmt_0118489143_1 = null;
        }
      } catch( SQLException e ) {
        if ( globdata.getDBMSData().getDBMSManager().wasSuccessful(e) == false )
        {
          sqlException = e;
          f_118489143_jdbc_dberror();
        }
      }
    }
    else {
      f_118489143_jdbc_dberror();
    }
  }
  
  public void f_118489143_jdbc_dberror()
  	throws ABException
  {
    globdata.getDBMSData().setSaveSQLException( sqlException );
    if ( sqlException != null )
    {
      globdata.getErrorData().setErrorMessage(sqlException);
    }
    globdata.getErrorData().setLastStatus( ErrorData.DB_ERROR_FL_LS );
    f_118489143_error();
  }
  public void f_118489143_error()
  	throws ABException
  {
    globdata.getErrorData().setStatus( ErrorData.FATAL_ERROR_FL_LS );
    if ( dl_0118489143.equals( ErrorData.SUCCEEDS_FL_LS ) == false )
    {
      globdata.getErrorData().setLastStatus( dl_0118489143 );
    }
    throw new ABException();
  }
  
  
  //  DISASSOC RELMM DOCMENTS
  public void f_4085()
  	throws ABException
  {
    globdata.getDBMSData().setV1Present( false );
    globdata.getDBMSData().setV2Present( true );
    globdata.getDBMSData().setCascade1( true );
    globdata.getDBMSData().setCascade2( false );
    globdata.getDBMSData().setProcessQueue( false );
    egolf6.F0004888.F0004888(iefRuntimeParm1, iefRuntimeParm2, globdata, pdaQueueCMCB, fk_scoring_recofk_golferuserid_039EF, 
      fk_scoring_recotime0_043EF, fk_scoring_recodate0_047EF, date0_005EF, time0_009EF, fk_golferuserid_029EF);
    if ( globdata.getErrorData().getStatus().equals( ErrorData.NONE_SF ) == false )
    {
      f_118489143_error();
    }
  }
  
  
  //  DISASSOC RELMM IS_MAINTAINED_BY
  public void f_1039()
  	throws ABException
  {
    globdata.getDBMSData().setV1Present( true );
    globdata.getDBMSData().setV2Present( false );
    globdata.getDBMSData().setCascade1( false );
    globdata.getDBMSData().setCascade2( true );
    globdata.getDBMSData().setProcessQueue( false );
    egolf6.F0003820.F0003820(iefRuntimeParm1, iefRuntimeParm2, globdata, pdaQueueCMCB, date0_005EF, time0_009EF, 
      fk_golferuserid_029EF, userid_053EF);
    if ( globdata.getErrorData().getStatus().equals( ErrorData.NONE_SF ) == false )
    {
      f_118489143_error();
    }
  }
  
  
  //  RESTRICT RELMM BETWEEN SCORING_RECORD AND SCORE_CARD
  public void f_4085_restrict()
  	throws ABException
  {
    sqlException = null;
    date0_003EF = date0_005EF;
    time0_007EF = time0_009EF;
    fk_golferuserid_027EF = fk_golferuserid_029EF;
    sqlException = null;
    try {
      if ( hstmt_0053477378_1 == null )
      {
        SQLStatement.setLength(0);
        
        SQLStatement.append("SELECT ");
        SQLStatement.append("`FK_SCORING_RECOFK_GOLFERUSERID`,");
        SQLStatement.append("`FK_SCORING_RECOTIME0`,");
        SQLStatement.append("`FK_SCORING_RECODATE0`");
        SQLStatement.append(" FROM ");
        SQLStatement.append("`SCORE_CARD`");
        SQLStatement.append(" WHERE ");
        SQLStatement.append("`FK_SCORING_RECODATE0` = ?");
        SQLStatement.append(" AND `FK_SCORING_RECOTIME0` = ?");
        SQLStatement.append(" AND `FK_SCORING_RECOFK_GOLFERUSERID` = ?");
        hstmt_0053477378_1 = globdata.getDBMSData().getDBMSManager().getStatement(globdata, iefRuntimeParm2, "golfer1", 
          SQLStatement.toString());
      }
      hstmt_0053477378_1.setDate(1, date0_003EF);
      hstmt_0053477378_1.setTime(2, time0_007EF);
      globdata.getDBMSData().getDBMSManager().bindParameterString("golfer1", hstmt_0053477378_1, 3, fk_golferuserid_027EF);
      hstmt_0053477378_1.execute();
      hstmt_0053477378_1_rs = hstmt_0053477378_1.getResultSet();
      hstmt_0053477378_1_cnt = hstmt_0053477378_1.getUpdateCount();
      if ( hstmt_0053477378_1_rs.next() == false )
      {
        throw new SQLException("No data found");
      }
      fk_scoring_recofk_golferuserid_037EF = globdata.getDBMSData().getDBMSManager().getStringFromResultSet("golfer1", 
        hstmt_0053477378_1_rs, 1);
      fk_scoring_recotime0_041EF = globdata.getDBMSData().getDBMSManager().getTimeFromResultSet(globdata, iefRuntimeParm2, "golfer1",
         hstmt_0053477378_1_rs, 2);
      fk_scoring_recodate0_045EF = hstmt_0053477378_1_rs.getDate(3);
    } catch( SQLException e ) {
      sqlException = e;
    }
    if ( (globdata.getDBMSData().getDBMSManager().wasSuccessful(sqlException)) || ((globdata.getDBMSData().getDBMSManager()
      .wasSuccessful(sqlException) && hstmt_0053477378_1_cnt > 1)) )
    {
      try {
        if ( hstmt_0053477378_1_rs != null )
        {
          hstmt_0053477378_1_rs.close();
          hstmt_0053477378_1_rs = null;
        }
        if ( hstmt_0053477378_1 != null )
        {
          hstmt_0053477378_1.close();
          hstmt_0053477378_1 = null;
        }
      } catch( SQLException e ) {
        if ( globdata.getDBMSData().getDBMSManager().wasSuccessful(e) == false )
        {
          sqlException = e;
          f_53477378_jdbc_dberror();
        }
      }
      dl_0118489143 = ErrorData.RESTRICT_ERROR_FL_LS;
      f_118489143_error();
    }
    else if ( !(globdata.getDBMSData().getDBMSManager().wasNoDataFound(sqlException)) )
    {
      f_53477378_jdbc_dberror();
    }
    else {
      try {
        if ( hstmt_0053477378_1_rs != null )
        {
          hstmt_0053477378_1_rs.close();
          hstmt_0053477378_1_rs = null;
        }
        if ( hstmt_0053477378_1 != null )
        {
          hstmt_0053477378_1.close();
          hstmt_0053477378_1 = null;
        }
      } catch( SQLException e ) {
        if ( globdata.getDBMSData().getDBMSManager().wasSuccessful(e) == false )
        {
          sqlException = e;
          f_53477378_jdbc_dberror();
        }
      }
    }
  }
  
  public void f_53477378_jdbc_dberror()
  	throws ABException
  {
    globdata.getDBMSData().setSaveSQLException( sqlException );
    dl_0118489143 = ErrorData.DB_ERROR_FL_LS;
    f_118489143_error();
  }
  
}// end class

