package egolf6;

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
//
//                    Source Code Generated by
//                           CA Gen 8.6
//
//      TARGET OS:  JVM                DBMS:  JDBC            
//
//      ACCESS METHOD:  JDBC                //
//        Name:  DELETE-GOLFER//
//      UserID:   mansour//
//        Date:  2017  Time:  22:14:54//
//    Copyright (c) 2017 CA Technologies. All rights reserved.//
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// Import Statements
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 
import java.lang.*;
import java.io.*;
import java.util.*;
import java.sql.*;
import java.math.*;
import com.ca.gen.vwrt.*;
import com.ca.gen.vwrt.types.*;
import com.ca.gen.abrt.*;
import com.ca.gen.abrt.functions.*;
import com.ca.gen.abrt.cascade.*;
import com.ca.gen.abrt.trace.*;
import com.ca.gen.exits.common.*;
 
public class E0001032 extends ABBase
{
  // internal flag used for delete/disassociate td action block
  String dl_0118489142;
  int relmm_cgvalue;
  DAQueue pdaQueueCMCB;
  // * * * * * * * * * * * * * * * * * * *
  // HOST VARIABLES FOR TABLE: GOLFER
  // * * * * * * * * * * * * * * * * * * *
  String userid_003EF;
  java.sql.Date date0_029EF;
  java.sql.Time time0_033EF;
  String fk_golferuserid_053EF;
  
  // * * * * * * * * * * * * * * * * * * *
  // VIEW FOR TABLE: GOLFER
  // * * * * * * * * * * * * * * * * * * *
  String userid_005EF;
  
  // * * * * * * * * * * * * * * * * * * *
  // VIEW FOR TABLE: SCORING_RECORD
  // * * * * * * * * * * * * * * * * * * *
  java.sql.Date date0_031EF;
  java.sql.Time time0_035EF;
  String fk_golferuserid_055EF;
  
  PreparedStatement hstmt_0053477376_1;
  ResultSet hstmt_0053477376_1_rs;
  int hstmt_0053477376_1_cnt;
  
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // MISC DECLARATIONS AND PROTOTYPES 
  //    FOLLOW AS NEEDED:             
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  PreparedStatement hstmt_0118489142_1;
  ResultSet hstmt_0118489142_1_rs;
  int hstmt_0118489142_1_cnt;
  
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  //  CONSTRUCTOR FOR THE CLASS       
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  public E0001032()
  {
    iefCGenRlse = "CA Gen 8.6";
    ssCopyright = "Copyright (c) 2017 CA Technologies. All rights reserved.";
    iefCGenDate = "2017/07/17";
    iefCGenTime = "22:14:54";
    iefCGenEncy = "9.2.A6";
    iefCGenUserId = "mansour";
    iefCGenModel = "EGOLF";
    iefCGenSubset = "ALL";
    iefCGenName = "E0001032";
  }
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // FUNCTION DECLARATIONS 
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  
  
  
  public static void E0001032(Object in_runtime_parm1, IRuntimePStepContext in_runtime_parm2, GlobData in_globdata, DAQueue 
    in_pdaQueueCMCB, int in_relmm_cgvalue, String parm_userid_005EF)
  {
    E0001032 obj = new E0001032();
    obj.iefRuntimeParm1 = in_runtime_parm1;
    obj.iefRuntimeParm2 = in_runtime_parm2;
    obj.globdata = in_globdata;
    obj.pdaQueueCMCB = in_pdaQueueCMCB;
    obj.relmm_cgvalue = in_relmm_cgvalue;
    obj.userid_005EF = parm_userid_005EF;
    obj.mainE0001032();
  }
  
  public void mainE0001032()
  {
    try {
      
      globdata.getStateData().setCurrentABId( "0118489142" );
      
      globdata.getStateData().setCurrentABName( "DELETE-GOLFER" );
      
      dl_0118489142 = ErrorData.SUCCEEDS_FL_LS;
      
      f_118489142_restrict();
      f_118489142_delete();
      f_118489142_evaluate();
    } catch( ABException e ) {
    }
  }
  
  
  public void f_118489142_evaluate()
  	throws ABException
  {
    f_0118489142_evaluate_exit: 
    {
      if ( relmm_cgvalue == 0 )
      {
        f_1039();
        break f_0118489142_evaluate_exit;
      }
      throw new ABException();
    }
  }
  
  
  public void f_118489142_restrict()
  	throws ABException
  {
    f_0118489142_restrict_exit: 
    {
      if ( relmm_cgvalue == 0 )
      {
        f_1039_restrict();
        break f_0118489142_restrict_exit;
      }
    }
  }
  
  
  //   DELETE GOLFER
  public void f_118489142_delete()
  	throws ABException
  {
    userid_003EF = userid_005EF;
    sqlException = null;
    try {
      if ( hstmt_0118489142_1 == null )
      {
        SQLStatement.setLength(0);
        
        SQLStatement.append("DELETE FROM ");
        SQLStatement.append("`GOLFER`");
        SQLStatement.append(" WHERE ");
        SQLStatement.append("`USERID` = ?");
        hstmt_0118489142_1 = globdata.getDBMSData().getDBMSManager().getStatement(globdata, iefRuntimeParm2, "golfer1", 
          SQLStatement.toString());
      }
      globdata.getDBMSData().getDBMSManager().bindParameterString("golfer1", hstmt_0118489142_1, 1, userid_003EF);
      hstmt_0118489142_1.execute();
      hstmt_0118489142_1_rs = hstmt_0118489142_1.getResultSet();
      hstmt_0118489142_1_cnt = hstmt_0118489142_1.getUpdateCount();
    } catch( SQLException e ) {
      sqlException = e;
    }
    if ( ((globdata.getDBMSData().getDBMSManager().wasNoDataFound(sqlException)) || ((globdata.getDBMSData().getDBMSManager()
      .wasSuccessful(sqlException) && (hstmt_0118489142_1_cnt == 0 || hstmt_0118489142_1_cnt == -1)))) || ((globdata.getDBMSData()
      .getDBMSManager().wasSuccessful(sqlException) && hstmt_0118489142_1_cnt == 1)) )
    {
      try {
        if ( hstmt_0118489142_1_rs != null )
        {
          hstmt_0118489142_1_rs.close();
          hstmt_0118489142_1_rs = null;
        }
        if ( hstmt_0118489142_1 != null )
        {
          hstmt_0118489142_1.close();
          hstmt_0118489142_1 = null;
        }
      } catch( SQLException e ) {
        if ( globdata.getDBMSData().getDBMSManager().wasSuccessful(e) == false )
        {
          sqlException = e;
          f_118489142_jdbc_dberror();
        }
      }
    }
    else {
      f_118489142_jdbc_dberror();
    }
  }
  
  public void f_118489142_jdbc_dberror()
  	throws ABException
  {
    globdata.getDBMSData().setSaveSQLException( sqlException );
    if ( sqlException != null )
    {
      globdata.getErrorData().setErrorMessage(sqlException);
    }
    globdata.getErrorData().setLastStatus( ErrorData.DB_ERROR_FL_LS );
    f_118489142_error();
  }
  public void f_118489142_error()
  	throws ABException
  {
    globdata.getErrorData().setStatus( ErrorData.FATAL_ERROR_FL_LS );
    if ( dl_0118489142.equals( ErrorData.SUCCEEDS_FL_LS ) == false )
    {
      globdata.getErrorData().setLastStatus( dl_0118489142 );
    }
    throw new ABException();
  }
  
  
  //  DISASSOC RELMM IS_MAINTAINED_BY
  public void f_1039()
  	throws ABException
  {
    globdata.getDBMSData().setV1Present( false );
    globdata.getDBMSData().setV2Present( true );
    globdata.getDBMSData().setCascade1( true );
    globdata.getDBMSData().setCascade2( false );
    globdata.getDBMSData().setProcessQueue( false );
    egolf6.F0003820.F0003820(iefRuntimeParm1, iefRuntimeParm2, globdata, pdaQueueCMCB, date0_031EF, time0_035EF, 
      fk_golferuserid_055EF, userid_005EF);
    if ( globdata.getErrorData().getStatus().equals( ErrorData.NONE_SF ) == false )
    {
      f_118489142_error();
    }
  }
  
  
  //  RESTRICT RELMM BETWEEN GOLFER AND SCORING_RECORD
  public void f_1039_restrict()
  	throws ABException
  {
    sqlException = null;
    userid_003EF = userid_005EF;
    sqlException = null;
    try {
      if ( hstmt_0053477376_1 == null )
      {
        SQLStatement.setLength(0);
        
        SQLStatement.append("SELECT ");
        SQLStatement.append("`DATE0`,");
        SQLStatement.append("`TIME0`,");
        SQLStatement.append("`FK_GOLFERUSERID`");
        SQLStatement.append(" FROM ");
        SQLStatement.append("`SCORING_RECORD`");
        SQLStatement.append(" WHERE ");
        SQLStatement.append("`FK_GOLFERUSERID` = ?");
        hstmt_0053477376_1 = globdata.getDBMSData().getDBMSManager().getStatement(globdata, iefRuntimeParm2, "golfer1", 
          SQLStatement.toString());
      }
      globdata.getDBMSData().getDBMSManager().bindParameterString("golfer1", hstmt_0053477376_1, 1, userid_003EF);
      hstmt_0053477376_1.execute();
      hstmt_0053477376_1_rs = hstmt_0053477376_1.getResultSet();
      hstmt_0053477376_1_cnt = hstmt_0053477376_1.getUpdateCount();
      if ( hstmt_0053477376_1_rs.next() == false )
      {
        throw new SQLException("No data found");
      }
      date0_029EF = hstmt_0053477376_1_rs.getDate(1);
      time0_033EF = globdata.getDBMSData().getDBMSManager().getTimeFromResultSet(globdata, iefRuntimeParm2, "golfer1", 
        hstmt_0053477376_1_rs, 2);
      fk_golferuserid_053EF = globdata.getDBMSData().getDBMSManager().getStringFromResultSet("golfer1", hstmt_0053477376_1_rs, 3);
    } catch( SQLException e ) {
      sqlException = e;
    }
    if ( (globdata.getDBMSData().getDBMSManager().wasSuccessful(sqlException)) || ((globdata.getDBMSData().getDBMSManager()
      .wasSuccessful(sqlException) && hstmt_0053477376_1_cnt > 1)) )
    {
      try {
        if ( hstmt_0053477376_1_rs != null )
        {
          hstmt_0053477376_1_rs.close();
          hstmt_0053477376_1_rs = null;
        }
        if ( hstmt_0053477376_1 != null )
        {
          hstmt_0053477376_1.close();
          hstmt_0053477376_1 = null;
        }
      } catch( SQLException e ) {
        if ( globdata.getDBMSData().getDBMSManager().wasSuccessful(e) == false )
        {
          sqlException = e;
          f_53477376_jdbc_dberror();
        }
      }
      dl_0118489142 = ErrorData.RESTRICT_ERROR_FL_LS;
      f_118489142_error();
    }
    else if ( !(globdata.getDBMSData().getDBMSManager().wasNoDataFound(sqlException)) )
    {
      f_53477376_jdbc_dberror();
    }
    else {
      try {
        if ( hstmt_0053477376_1_rs != null )
        {
          hstmt_0053477376_1_rs.close();
          hstmt_0053477376_1_rs = null;
        }
        if ( hstmt_0053477376_1 != null )
        {
          hstmt_0053477376_1.close();
          hstmt_0053477376_1 = null;
        }
      } catch( SQLException e ) {
        if ( globdata.getDBMSData().getDBMSManager().wasSuccessful(e) == false )
        {
          sqlException = e;
          f_53477376_jdbc_dberror();
        }
      }
    }
  }
  
  public void f_53477376_jdbc_dberror()
  	throws ABException
  {
    globdata.getDBMSData().setSaveSQLException( sqlException );
    dl_0118489142 = ErrorData.DB_ERROR_FL_LS;
    f_118489142_error();
  }
  
}// end class

