package egolf6;

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
//
//                    Source Code Generated by
//                           CA Gen 8.6
//
//      TARGET OS:  JVM                DBMS:  JDBC            
//
//      ACCESS METHOD:  JDBC                //
//        Name:  DIS-SCORING_RECORD-GOLFER//
//      UserID:   mansour//
//        Date:  2017  Time:  22:14:54//
//    Copyright (c) 2017 CA Technologies. All rights reserved.//
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// Import Statements
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 
import java.lang.*;
import java.io.*;
import java.util.*;
import java.sql.*;
import java.math.*;
import com.ca.gen.vwrt.*;
import com.ca.gen.vwrt.types.*;
import com.ca.gen.abrt.*;
import com.ca.gen.abrt.functions.*;
import com.ca.gen.abrt.cascade.*;
import com.ca.gen.abrt.trace.*;
import com.ca.gen.exits.common.*;
 
public class F0003820 extends ABBase
{
  // internal flag used for delete/disassociate td action block
  String dl_0203423770;
  int relmm_cgvalue;
  DAQueue pdaQueueCMCB;
  
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // MISC DECLARATIONS AND PROTOTYPES 
  //    FOLLOW AS NEEDED:             
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // * * * * * * * * * * * * * * * * * * *
  // VIEW FOR TABLE: SCORING_RECORD
  // * * * * * * * * * * * * * * * * * * *
  java.sql.Date date0_005EF;
  java.sql.Time time0_009EF;
  String fk_golferuserid_029EF;
  
  // * * * * * * * * * * * * * * * * * * *
  // TIDDAQUE object array for Table E0001035
  // * * * * * * * * * * * * * * * * * * *
  DAQueueObject [] daq_scoring_record_001DR = DAQueueObject.getArrayInstance(3);
  
  // * * * * * * * * * * * * * * * * * * *
  // VIEW FOR TABLE: GOLFER
  // * * * * * * * * * * * * * * * * * * *
  String userid_035EF;
  
  // * * * * * * * * * * * * * * * * * * *
  // TIDDAQUE object array for Table E0001032
  // * * * * * * * * * * * * * * * * * * *
  DAQueueObject [] daq_golfer_031DR = DAQueueObject.getArrayInstance(1);
  
  
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  //  CONSTRUCTOR FOR THE CLASS       
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  public F0003820()
  {
    iefCGenRlse = "CA Gen 8.6";
    ssCopyright = "Copyright (c) 2017 CA Technologies. All rights reserved.";
    iefCGenDate = "2017/07/17";
    iefCGenTime = "22:14:54";
    iefCGenEncy = "9.2.A6";
    iefCGenUserId = "mansour";
    iefCGenModel = "EGOLF";
    iefCGenSubset = "ALL";
    iefCGenName = "F0003820";
  }
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // FUNCTION DECLARATIONS 
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  
  
  
  public static void F0003820(Object in_runtime_parm1, IRuntimePStepContext in_runtime_parm2, GlobData in_globdata, DAQueue 
    in_pdaQueueCMCB, java.sql.Date parm_date0_005EF, java.sql.Time parm_time0_009EF, String parm_fk_golferuserid_029EF, String 
    parm_userid_035EF)
  {
    F0003820 obj = new F0003820();
    obj.iefRuntimeParm1 = in_runtime_parm1;
    obj.iefRuntimeParm2 = in_runtime_parm2;
    obj.globdata = in_globdata;
    obj.pdaQueueCMCB = in_pdaQueueCMCB;
    obj.date0_005EF = parm_date0_005EF;
    obj.time0_009EF = parm_time0_009EF;
    obj.fk_golferuserid_029EF = parm_fk_golferuserid_029EF;
    obj.userid_035EF = parm_userid_035EF;
    obj.mainF0003820();
  }
  
  public void mainF0003820()
  {
    try {
      
      globdata.getStateData().setCurrentABId( "0203423770" );
      
      globdata.getStateData().setCurrentABName( "DIS-SCORING_RECORD-GOLFER" );
      
      dl_0203423770 = ErrorData.SUCCEEDS_FL_LS;
      
      f_203423770_evaluate();
    } catch( ABException e ) {
    }
  }
  
  
  public void f_203423770_error()
  	throws ABException
  {
    globdata.getErrorData().setStatus( ErrorData.FATAL_ERROR_FL_LS );
    if ( dl_0203423770.equals( ErrorData.SUCCEEDS_FL_LS ) == false )
    {
      globdata.getErrorData().setLastStatus( dl_0203423770 );
    }
    throw new ABException();
  }
  
  
  public void f_203423770_evaluate()
  	throws ABException
  {
    if ( (globdata.getDBMSData().getV1Present() == true) && (globdata.getDBMSData().getV2Present() == false) )
    {
    }
    else if ( (globdata.getDBMSData().getV1Present() == false) && (globdata.getDBMSData().getV2Present() == true) )
    {
    }
    else if ( (globdata.getDBMSData().getV1Present() == true) && (globdata.getDBMSData().getV2Present() == true) )
    {
      if ( (globdata.getDBMSData().getCascade1() == true) && (globdata.getDBMSData().getCascade2() == true) )
      {
        f_53477377_qdelete();
      }
      else if ( (globdata.getDBMSData().getCascade1() == true) && (globdata.getDBMSData().getCascade2() == false) )
      {
        if ( globdata.getDBMSData().getProcessQueue() == true )
        {
          f_53477377_qdelete();
        }
      }
      else if ( (globdata.getDBMSData().getCascade1() == false) && (globdata.getDBMSData().getCascade2() == true) )
      {
        if ( globdata.getDBMSData().getProcessQueue() == true )
        {
        }
      }
    }
  }
  
  
  // Delete the source record from SCORING_RECORD
  public void f_53477377_qdelete()
  	throws ABException
  {
    globdata.getDBMSData().setProcessQueue( false );
    relmm_cgvalue = 1039;
    egolf6.E0001035.E0001035(iefRuntimeParm1, iefRuntimeParm2, globdata, pdaQueueCMCB, relmm_cgvalue, date0_005EF, time0_009EF, 
      fk_golferuserid_029EF);
    if ( globdata.getErrorData().getStatus().equals( ErrorData.NONE_SF ) == false )
    {
      f_203423770_error();
    }
  }
  
  public void f_23068713_jdbc_dberror()
  	throws ABException
  {
    if ( sqlException != null )
    {
      globdata.getErrorData().setErrorMessage(sqlException);
    }
    dl_0203423770 = ErrorData.DB_ERROR_FL_LS;
    f_203423770_error();
  }
  
}// end class

