package egolf6;

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
//
//                    Source Code Generated by
//                           CA Gen 8.6
//
//      TARGET OS:  JVM                DBMS:  JDBC            
//
//      ACCESS METHOD:  JDBC                //
//        Name:  DIS-SCORE_CARD-SCORING_RECORD//
//      UserID:   mansour//
//        Date:  2017  Time:  22:14:54//
//    Copyright (c) 2017 CA Technologies. All rights reserved.//
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// Import Statements
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 
import java.lang.*;
import java.io.*;
import java.util.*;
import java.sql.*;
import java.math.*;
import com.ca.gen.vwrt.*;
import com.ca.gen.vwrt.types.*;
import com.ca.gen.abrt.*;
import com.ca.gen.abrt.functions.*;
import com.ca.gen.abrt.cascade.*;
import com.ca.gen.abrt.trace.*;
import com.ca.gen.exits.common.*;
 
public class F0004888 extends ABBase
{
  // internal flag used for delete/disassociate td action block
  String dl_0203423753;
  int relmm_cgvalue;
  DAQueue pdaQueueCMCB;
  
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // MISC DECLARATIONS AND PROTOTYPES 
  //    FOLLOW AS NEEDED:             
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // * * * * * * * * * * * * * * * * * * *
  // VIEW FOR TABLE: SCORE_CARD
  // * * * * * * * * * * * * * * * * * * *
  String fk_scoring_recofk_golferuserid_009EF;
  java.sql.Time fk_scoring_recotime0_013EF;
  java.sql.Date fk_scoring_recodate0_017EF;
  
  // * * * * * * * * * * * * * * * * * * *
  // TIDDAQUE object array for Table E0004080
  // * * * * * * * * * * * * * * * * * * *
  DAQueueObject [] daq_score_card_001DR = DAQueueObject.getArrayInstance(3);
  
  // * * * * * * * * * * * * * * * * * * *
  // VIEW FOR TABLE: SCORING_RECORD
  // * * * * * * * * * * * * * * * * * * *
  java.sql.Date date0_023EF;
  java.sql.Time time0_027EF;
  String fk_golferuserid_047EF;
  
  // * * * * * * * * * * * * * * * * * * *
  // TIDDAQUE object array for Table E0001035
  // * * * * * * * * * * * * * * * * * * *
  DAQueueObject [] daq_scoring_record_019DR = DAQueueObject.getArrayInstance(3);
  
  
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  //  CONSTRUCTOR FOR THE CLASS       
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  public F0004888()
  {
    iefCGenRlse = "CA Gen 8.6";
    ssCopyright = "Copyright (c) 2017 CA Technologies. All rights reserved.";
    iefCGenDate = "2017/07/17";
    iefCGenTime = "22:14:54";
    iefCGenEncy = "9.2.A6";
    iefCGenUserId = "mansour";
    iefCGenModel = "EGOLF";
    iefCGenSubset = "ALL";
    iefCGenName = "F0004888";
  }
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // FUNCTION DECLARATIONS 
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  
  
  
  public static void F0004888(Object in_runtime_parm1, IRuntimePStepContext in_runtime_parm2, GlobData in_globdata, DAQueue 
    in_pdaQueueCMCB, String parm_fk_scoring_recofk_golferuserid_009EF, java.sql.Time parm_fk_scoring_recotime0_013EF, java.sql.Date 
    parm_fk_scoring_recodate0_017EF, java.sql.Date parm_date0_023EF, java.sql.Time parm_time0_027EF, String 
    parm_fk_golferuserid_047EF)
  {
    F0004888 obj = new F0004888();
    obj.iefRuntimeParm1 = in_runtime_parm1;
    obj.iefRuntimeParm2 = in_runtime_parm2;
    obj.globdata = in_globdata;
    obj.pdaQueueCMCB = in_pdaQueueCMCB;
    obj.fk_scoring_recofk_golferuserid_009EF = parm_fk_scoring_recofk_golferuserid_009EF;
    obj.fk_scoring_recotime0_013EF = parm_fk_scoring_recotime0_013EF;
    obj.fk_scoring_recodate0_017EF = parm_fk_scoring_recodate0_017EF;
    obj.date0_023EF = parm_date0_023EF;
    obj.time0_027EF = parm_time0_027EF;
    obj.fk_golferuserid_047EF = parm_fk_golferuserid_047EF;
    obj.mainF0004888();
  }
  
  public void mainF0004888()
  {
    try {
      
      globdata.getStateData().setCurrentABId( "0203423753" );
      
      globdata.getStateData().setCurrentABName( "DIS-SCORE_CARD-SCORING_RECORD" );
      
      dl_0203423753 = ErrorData.SUCCEEDS_FL_LS;
      
      f_203423753_evaluate();
    } catch( ABException e ) {
    }
  }
  
  
  public void f_203423753_error()
  	throws ABException
  {
    globdata.getErrorData().setStatus( ErrorData.FATAL_ERROR_FL_LS );
    if ( dl_0203423753.equals( ErrorData.SUCCEEDS_FL_LS ) == false )
    {
      globdata.getErrorData().setLastStatus( dl_0203423753 );
    }
    throw new ABException();
  }
  
  
  public void f_203423753_evaluate()
  	throws ABException
  {
    if ( (globdata.getDBMSData().getV1Present() == true) && (globdata.getDBMSData().getV2Present() == false) )
    {
    }
    else if ( (globdata.getDBMSData().getV1Present() == false) && (globdata.getDBMSData().getV2Present() == true) )
    {
    }
    else if ( (globdata.getDBMSData().getV1Present() == true) && (globdata.getDBMSData().getV2Present() == true) )
    {
      if ( (globdata.getDBMSData().getCascade1() == true) && (globdata.getDBMSData().getCascade2() == true) )
      {
        f_53477379_qdelete();
      }
      else if ( (globdata.getDBMSData().getCascade1() == true) && (globdata.getDBMSData().getCascade2() == false) )
      {
        if ( globdata.getDBMSData().getProcessQueue() == true )
        {
          f_53477379_qdelete();
        }
      }
      else if ( (globdata.getDBMSData().getCascade1() == false) && (globdata.getDBMSData().getCascade2() == true) )
      {
        if ( globdata.getDBMSData().getProcessQueue() == true )
        {
        }
      }
    }
  }
  
  
  // Delete the source record from SCORE_CARD
  public void f_53477379_qdelete()
  	throws ABException
  {
    globdata.getDBMSData().setProcessQueue( false );
    relmm_cgvalue = 4085;
    egolf6.E0004080.E0004080(iefRuntimeParm1, iefRuntimeParm2, globdata, pdaQueueCMCB, relmm_cgvalue, 
      fk_scoring_recofk_golferuserid_009EF, fk_scoring_recotime0_013EF, fk_scoring_recodate0_017EF);
    if ( globdata.getErrorData().getStatus().equals( ErrorData.NONE_SF ) == false )
    {
      f_203423753_error();
    }
  }
  
  public void f_23068687_jdbc_dberror()
  	throws ABException
  {
    if ( sqlException != null )
    {
      globdata.getErrorData().setErrorMessage(sqlException);
    }
    dl_0203423753 = ErrorData.DB_ERROR_FL_LS;
    f_203423753_error();
  }
  
}// end class

