                                                                
/****************************************************************
 *
 *                    Source Code Generated by
 *                           CA Gen 8.6
 *
 *    Copyright (c) 2017 CA Technologies. All rights reserved.
 *
 *      TARGET OS:  WINDOWS            DBMS:  MS/SQL          
 *
 *      ACCESS METHOD:  ODBC/ADO.NET        
 *
 *        Name:  DELETE-GOLFER
 *
 *      UserID:   mansour
 *
 *        Date:  2017/07/17  Time:  22:14:04
 *
 ***************************************************************/
/****************************************************************
 Data declarations
 ***************************************************************/
static char ief_cgen_rlse[] = "CA Gen 8.6";
static char * ss_copyright = "Copyright (c) 2017 CA Technologies. All rights reserved.";
static char ief_cgen_date[] = "2017/07/17";
static char ief_cgen_time[] = "22:14:04";
static char ief_pgmrname[9] = " mansour";
#define TGT_ANSI
#define TGT_INTERNAL
#define TGT_DASG 1
#define TGT_ODBC 1
#include <tiabinc.h>
/***************************************************************
 * internal flag used for delete/disassociate td action block  *
 ***************************************************************/
TGTSTATIC char dl_0118489142[3];
static struct golfer_001dr  *pgolfer_001dr;
static void f_118489142_delete(void);
static TIHSTMT hstmt_0118489142_1 = {SQL_NULL_HSTMT, NULL};
static void f_118489142_odbc_dberror(TIHSTMT * tihstmt);
static void f_118489142_evaluate(void);
static char long64bit_len[5];



static UCHAR FAR userid_003ef[9] /* 8 + 1 */;

/*    View for Table GOLFER */
static struct golfer_001dr
{
UCHAR FAR userid_005ef[9] /* 8 + 1 */;
} golfer_001dr;

static void f_118489142_error(void);

void E0001032(char  *in_runtime_parm1, char  *in_runtime_parm2, 
struct ief_globdata  *in_globdata, struct DA_QUEUE_CMCB  *in_pda_queue_cmcb, 
struct golfer_001dr  *in_golfer_001dr, 
long  *prelmm_cgvalue) 
{
ief_runtime_parm1 = in_runtime_parm1;
ief_runtime_parm2 = in_runtime_parm2;
globdata = in_globdata;
pda_queue_cmcb = in_pda_queue_cmcb;
pgolfer_001dr = in_golfer_001dr;
relmm_cgvalue = *prelmm_cgvalue;
 if (setjmp(excp_jumpbuf))
{
}
 else {
strcpy(globdata->psmgr_debug_data.cur_ab_id, "0118489142");

strcpy(globdata->psmgr_debug_data.cur_ab_name, "DELETE-GOLFER");

strcpy(dl_0118489142, succeeds);

 if (info == 0)
{
info = (ODBC_INFO*)getODBCHandles();
}
f_118489142_delete();
f_118489142_evaluate();
}
return;
}



/*   DELETE GOLFER */
static void f_118489142_delete(void)
{
Tistrcpy(userid_003ef, pgolfer_001dr->userid_005ef, sizeof(userid_003ef));
info->sqlca->rc = TiodbcAllocStmt(&hstmt_0118489142_1,
    "hstmt_0118489142_1",
    FALSE);
 if (ODBC_SUCCESSFUL(info->sqlca->rc))
 if (!(hstmt_0118489142_1.pODBChstmt->reuse))
{
strcpy(odbc_stmt, "DELETE FROM ");
strcat(odbc_stmt, "`GOLFER`");
strcat(odbc_stmt, " WHERE ");
strcat(odbc_stmt, "`USERID` = ?");
info->sqlca->rc = TiodbcPrepare(&hstmt_0118489142_1, odbc_stmt);
 if (ODBC_SUCCESSFUL(info->sqlca->rc))
info->sqlca->rc = TiodbcParameter(&hstmt_0118489142_1, 1,
    "", "GOLFER", "USERID");
 if (ODBC_SUCCESSFUL(info->sqlca->rc))
info->sqlca->rc = SQLBindParameter(hstmt_0118489142_1.hstmt, 1,
SQL_PARAM_INPUT, SQL_C_CHAR, info->sqlType, sizeof(userid_003ef)-1,
info->scale,  userid_003ef, sizeof(userid_003ef), NULL);
 if (ODBC_SUCCESSFUL(info->sqlca->rc))
hstmt_0118489142_1.pODBChstmt->reuse = TRUE;
}
 if (ODBC_SUCCESSFUL(info->sqlca->rc))
info->sqlca->rc = SQLExecute(hstmt_0118489142_1.hstmt);
 if (ODBC_NOT_SUCCESSFUL(info->sqlca->rc))
   f_118489142_odbc_dberror(&hstmt_0118489142_1);
 if (((ODBC_NOT_FOUND(info->sqlca->rc)) ||
    ((ODBC_SUCCESSFUL(info->sqlca->rc) &&
ODBC_SUCCESSFUL(SQLRowCount(hstmt_0118489142_1.hstmt, &odbcRowCount)) &&
odbcRowCount == 0))) ||
    ((ODBC_SUCCESSFUL(info->sqlca->rc) &&
ODBC_SUCCESSFUL((SQLRowCount(hstmt_0118489142_1.hstmt, &odbcRowCount))) &&
odbcRowCount == 1)))
{
info->sqlca->rc = TiodbcFreeStmt(&hstmt_0118489142_1);
 if (ODBC_NOT_SUCCESSFUL(info->sqlca->rc))
   f_118489142_odbc_dberror(&hstmt_0118489142_1);
}
 else {
f_118489142_odbc_dberror(&hstmt_0118489142_1);
}
}

static void f_118489142_odbc_dberror(TIHSTMT * tihstmt)
{
TiodbcError(tihstmt);
memcpy(globdata->psmgr_dasg_data.save_sqlca,
    info->sqlca,
    sizeof(* info->sqlca));
strcpy(globdata->psmgr_dasg_data.last_status, db_error);
f_118489142_error();
}


static void f_118489142_evaluate(void)
{
 if (relmm_cgvalue == 0L)
{
goto f_0118489142_evaluate_exit;
}
longjmp(excp_jumpbuf, TRACE_EXCEPTION);
f_0118489142_evaluate_exit: 
;
}


static void f_118489142_error(void)
{
strcpy(globdata->psmgr_dasg_data.status_flag, fatal_error);
 if (strcmp(dl_0118489142, succeeds) != 0)
strcpy(globdata->psmgr_dasg_data.last_status, dl_0118489142);
longjmp(excp_jumpbuf, FUNCTION_EXCEPTION);
}
