                                                                
/****************************************************************
 *
 *                    Source Code Generated by
 *                           CA Gen 8.6
 *
 *    Copyright (c) 2017 CA Technologies. All rights reserved.
 *
 *      TARGET OS:  WINDOWS            DBMS:  MS/SQL          
 *
 *      ACCESS METHOD:  ODBC/ADO.NET        
 *
 *        Name:  DELETE-SCORING_RECORD
 *
 *      UserID:   mansour
 *
 *        Date:  2017/07/17  Time:  22:14:04
 *
 ***************************************************************/
/****************************************************************
 Data declarations
 ***************************************************************/
static char ief_cgen_rlse[] = "CA Gen 8.6";
static char * ss_copyright = "Copyright (c) 2017 CA Technologies. All rights reserved.";
static char ief_cgen_date[] = "2017/07/17";
static char ief_cgen_time[] = "22:14:04";
static char ief_pgmrname[9] = " mansour";
#define TGT_ANSI
#define TGT_INTERNAL
#define TGT_DASG 1
#define TGT_ODBC 1
#include <tiabinc.h>
/***************************************************************
 * internal flag used for delete/disassociate td action block  *
 ***************************************************************/
TGTSTATIC char dl_0118489143[3];
static struct scoring_reco_001dr  *pscoring_reco_001dr;
static void f_118489143_delete(void);
static TIHSTMT hstmt_0118489143_1 = {SQL_NULL_HSTMT, NULL};
static void f_118489143_odbc_dberror(TIHSTMT * tihstmt);
static void f_118489143_evaluate(void);
static void f_1039(void);
/*    View for Table GOLFER */
static struct golfer_049dr
{
UCHAR FAR userid_053ef[9] /* 8 + 1 */;
} golfer_049dr;

static char long64bit_len[5];



static DATE_STRUCT date0_003ef;
static TIMESTAMP_STRUCT time0_007ef;
static UCHAR FAR fk_golferuse_027ef[9] /* 8 + 1 */;

/*    View for Table SCORING_RECORD */
static struct scoring_reco_001dr
{
DATE_STRUCT date0_005ef;
TIMESTAMP_STRUCT time0_009ef;
UCHAR FAR fk_golferuse_029ef[9] /* 8 + 1 */;
} scoring_reco_001dr;

static void f_118489143_error(void);
void F0003820();


void E0001035(char  *in_runtime_parm1, char  *in_runtime_parm2, 
struct ief_globdata  *in_globdata, struct DA_QUEUE_CMCB  *in_pda_queue_cmcb, 
struct scoring_reco_001dr  *in_scoring_reco_001dr, 
long  *prelmm_cgvalue) 
{
ief_runtime_parm1 = in_runtime_parm1;
ief_runtime_parm2 = in_runtime_parm2;
globdata = in_globdata;
pda_queue_cmcb = in_pda_queue_cmcb;
pscoring_reco_001dr = in_scoring_reco_001dr;
relmm_cgvalue = *prelmm_cgvalue;
 if (setjmp(excp_jumpbuf))
{
}
 else {
strcpy(globdata->psmgr_debug_data.cur_ab_id, "0118489143");

strcpy(globdata->psmgr_debug_data.cur_ab_name, "DELETE-SCORING_RECORD");

strcpy(dl_0118489143, succeeds);

 if (info == 0)
{
info = (ODBC_INFO*)getODBCHandles();
}
f_118489143_delete();
f_118489143_evaluate();
}
return;
}



/*   DELETE SCORING_RECORD */
static void f_118489143_delete(void)
{
memcpy(&date0_003ef, &pscoring_reco_001dr->date0_005ef, sizeof(date0_003ef));
memcpy(&time0_007ef, &pscoring_reco_001dr->time0_009ef, sizeof(time0_007ef));
Tistrcpy(fk_golferuse_027ef,
    pscoring_reco_001dr->fk_golferuse_029ef,
    sizeof(fk_golferuse_027ef));
info->sqlca->rc = TiodbcAllocStmt(&hstmt_0118489143_1,
    "hstmt_0118489143_1",
    FALSE);
 if (ODBC_SUCCESSFUL(info->sqlca->rc))
 if (!(hstmt_0118489143_1.pODBChstmt->reuse))
{
strcpy(odbc_stmt, "DELETE FROM ");
strcat(odbc_stmt, "`SCORING_RECORD`");
strcat(odbc_stmt, " WHERE ");
strcat(odbc_stmt, "`DATE0` = ?");
strcat(odbc_stmt, " AND `TIME0` = ?");
strcat(odbc_stmt, " AND `FK_GOLFERUSERID` = ?");
info->sqlca->rc = TiodbcPrepare(&hstmt_0118489143_1, odbc_stmt);
 if (ODBC_SUCCESSFUL(info->sqlca->rc))
info->sqlca->rc = TiodbcParameter(&hstmt_0118489143_1, 1,
    "", "SCORING_RECORD", "DATE0");
 if (ODBC_SUCCESSFUL(info->sqlca->rc))
info->sqlca->rc = SQLBindParameter(hstmt_0118489143_1.hstmt, 1,
SQL_PARAM_INPUT, SQL_C_TYPE_DATE, info->sqlType, info->precision, info->scale,
&date0_003ef, sizeof(date0_003ef), NULL);
 if (ODBC_SUCCESSFUL(info->sqlca->rc))
info->sqlca->rc = TiodbcParameter(&hstmt_0118489143_1, 2,
    "", "SCORING_RECORD", "TIME0");
 if (ODBC_SUCCESSFUL(info->sqlca->rc))
info->sqlca->rc = SQLBindParameter(hstmt_0118489143_1.hstmt, 2,
SQL_PARAM_INPUT, SQL_C_TYPE_TIMESTAMP, info->sqlType, info->precision,
info->scale, &time0_007ef, sizeof(time0_007ef), NULL);
 if (ODBC_SUCCESSFUL(info->sqlca->rc))
info->sqlca->rc = TiodbcParameter(&hstmt_0118489143_1, 3,
    "", "SCORING_RECORD", "FK_GOLFERUSERID");
 if (ODBC_SUCCESSFUL(info->sqlca->rc))
info->sqlca->rc = SQLBindParameter(hstmt_0118489143_1.hstmt, 3,
SQL_PARAM_INPUT, SQL_C_CHAR, info->sqlType, sizeof(fk_golferuse_027ef)-1,
info->scale,  fk_golferuse_027ef, sizeof(fk_golferuse_027ef), NULL);
 if (ODBC_SUCCESSFUL(info->sqlca->rc))
hstmt_0118489143_1.pODBChstmt->reuse = TRUE;
}
 if (ODBC_SUCCESSFUL(info->sqlca->rc))
info->sqlca->rc = SQLExecute(hstmt_0118489143_1.hstmt);
 if (ODBC_NOT_SUCCESSFUL(info->sqlca->rc))
   f_118489143_odbc_dberror(&hstmt_0118489143_1);
 if (((ODBC_NOT_FOUND(info->sqlca->rc)) ||
    ((ODBC_SUCCESSFUL(info->sqlca->rc) &&
ODBC_SUCCESSFUL(SQLRowCount(hstmt_0118489143_1.hstmt, &odbcRowCount)) &&
odbcRowCount == 0))) ||
    ((ODBC_SUCCESSFUL(info->sqlca->rc) &&
ODBC_SUCCESSFUL((SQLRowCount(hstmt_0118489143_1.hstmt, &odbcRowCount))) &&
odbcRowCount == 1)))
{
info->sqlca->rc = TiodbcFreeStmt(&hstmt_0118489143_1);
 if (ODBC_NOT_SUCCESSFUL(info->sqlca->rc))
   f_118489143_odbc_dberror(&hstmt_0118489143_1);
}
 else {
f_118489143_odbc_dberror(&hstmt_0118489143_1);
}
}

static void f_118489143_odbc_dberror(TIHSTMT * tihstmt)
{
TiodbcError(tihstmt);
memcpy(globdata->psmgr_dasg_data.save_sqlca,
    info->sqlca,
    sizeof(* info->sqlca));
strcpy(globdata->psmgr_dasg_data.last_status, db_error);
f_118489143_error();
}


static void f_118489143_evaluate(void)
{
 if (relmm_cgvalue == 0L)
{
f_1039();
goto f_0118489143_evaluate_exit;
}
 if (relmm_cgvalue == 4085L)
{
f_1039();
goto f_0118489143_evaluate_exit;
}
longjmp(excp_jumpbuf, TRACE_EXCEPTION);
f_0118489143_evaluate_exit: 
;
}


static void f_118489143_error(void)
{
strcpy(globdata->psmgr_dasg_data.status_flag, fatal_error);
 if (strcmp(dl_0118489143, succeeds) != 0)
strcpy(globdata->psmgr_dasg_data.last_status, dl_0118489143);
longjmp(excp_jumpbuf, FUNCTION_EXCEPTION);
}


/*  DISASSOC RELMM IS_MAINTAINED_BY */
static void f_1039(void)
{
globdata->v1present = 'Y';
globdata->v2present = 'N';
globdata->cascade1 = 'N';
globdata->cascade2 = 'Y';
globdata->processq_flag = 'N';
F0003820(ief_runtime_parm1,
    ief_runtime_parm2,
    globdata,
    pda_queue_cmcb,
    pscoring_reco_001dr,
    &golfer_049dr);
 if (strcmp(globdata->psmgr_dasg_data.status_flag, "  ") != 0)
f_118489143_error();
}
