                                                                
/****************************************************************
 *
 *                    Source Code Generated by
 *                           CA Gen 8.6
 *
 *    Copyright (c) 2017 CA Technologies. All rights reserved.
 *
 *      TARGET OS:  WINDOWS            DBMS:  MS/SQL          
 *
 *      ACCESS METHOD:  ODBC/ADO.NET        
 *
 *        Name:  DELETE-SCORE_CARD
 *
 *      UserID:   mansour
 *
 *        Date:  2017/07/17  Time:  22:14:04
 *
 ***************************************************************/
/****************************************************************
 Data declarations
 ***************************************************************/
static char ief_cgen_rlse[] = "CA Gen 8.6";
static char * ss_copyright = "Copyright (c) 2017 CA Technologies. All rights reserved.";
static char ief_cgen_date[] = "2017/07/17";
static char ief_cgen_time[] = "22:14:04";
static char ief_pgmrname[9] = " mansour";
#define TGT_ANSI
#define TGT_INTERNAL
#define TGT_DASG 1
#define TGT_ODBC 1
#include <tiabinc.h>
/***************************************************************
 * internal flag used for delete/disassociate td action block  *
 ***************************************************************/
TGTSTATIC char dl_0118489145[3];
static struct score_card_001dr  *pscore_card_001dr;
static void f_118489145_delete(void);
static TIHSTMT hstmt_0118489145_1 = {SQL_NULL_HSTMT, NULL};
static void f_118489145_odbc_dberror(TIHSTMT * tihstmt);
static void f_118489145_evaluate(void);
static void f_4085(void);
/*    View for Table SCORING_RECORD */
static struct scoring_reco_019dr
{
DATE_STRUCT date0_023ef;
TIMESTAMP_STRUCT time0_027ef;
UCHAR FAR fk_golferuse_047ef[9] /* 8 + 1 */;
} scoring_reco_019dr;

static char long64bit_len[5];



static UCHAR FAR fk_scoring_r_007ef[9] /* 8 + 1 */;
static TIMESTAMP_STRUCT fk_scoring_r_011ef;
static DATE_STRUCT fk_scoring_r_015ef;

/*    View for Table SCORE_CARD */
static struct score_card_001dr
{
UCHAR FAR fk_scoring_r_009ef[9] /* 8 + 1 */;
TIMESTAMP_STRUCT fk_scoring_r_013ef;
DATE_STRUCT fk_scoring_r_017ef;
} score_card_001dr;

static void f_118489145_error(void);
void F0004888();


void E0004080(char  *in_runtime_parm1, char  *in_runtime_parm2, 
struct ief_globdata  *in_globdata, struct DA_QUEUE_CMCB  *in_pda_queue_cmcb, 
struct score_card_001dr  *in_score_card_001dr, 
long  *prelmm_cgvalue) 
{
ief_runtime_parm1 = in_runtime_parm1;
ief_runtime_parm2 = in_runtime_parm2;
globdata = in_globdata;
pda_queue_cmcb = in_pda_queue_cmcb;
pscore_card_001dr = in_score_card_001dr;
relmm_cgvalue = *prelmm_cgvalue;
 if (setjmp(excp_jumpbuf))
{
}
 else {
strcpy(globdata->psmgr_debug_data.cur_ab_id, "0118489145");

strcpy(globdata->psmgr_debug_data.cur_ab_name, "DELETE-SCORE_CARD");

strcpy(dl_0118489145, succeeds);

 if (info == 0)
{
info = (ODBC_INFO*)getODBCHandles();
}
f_118489145_delete();
f_118489145_evaluate();
}
return;
}



/*   DELETE SCORE_CARD */
static void f_118489145_delete(void)
{
Tistrcpy(fk_scoring_r_007ef,
    pscore_card_001dr->fk_scoring_r_009ef,
    sizeof(fk_scoring_r_007ef));
memcpy(&fk_scoring_r_011ef,
    &pscore_card_001dr->fk_scoring_r_013ef,
    sizeof(fk_scoring_r_011ef));
memcpy(&fk_scoring_r_015ef,
    &pscore_card_001dr->fk_scoring_r_017ef,
    sizeof(fk_scoring_r_015ef));
info->sqlca->rc = TiodbcAllocStmt(&hstmt_0118489145_1,
    "hstmt_0118489145_1",
    FALSE);
 if (ODBC_SUCCESSFUL(info->sqlca->rc))
 if (!(hstmt_0118489145_1.pODBChstmt->reuse))
{
strcpy(odbc_stmt, "DELETE FROM ");
strcat(odbc_stmt, "`SCORE_CARD`");
strcat(odbc_stmt, " WHERE ");
strcat(odbc_stmt, "`FK_SCORING_RECOFK_GOLFERUSERID` = ?");
strcat(odbc_stmt, " AND `FK_SCORING_RECOTIME0` = ?");
strcat(odbc_stmt, " AND `FK_SCORING_RECODATE0` = ?");
info->sqlca->rc = TiodbcPrepare(&hstmt_0118489145_1, odbc_stmt);
 if (ODBC_SUCCESSFUL(info->sqlca->rc))
info->sqlca->rc = TiodbcParameter(&hstmt_0118489145_1, 1,
    "", "SCORE_CARD", "FK_SCORING_RECOFK_GOLFERUSERID");
 if (ODBC_SUCCESSFUL(info->sqlca->rc))
info->sqlca->rc = SQLBindParameter(hstmt_0118489145_1.hstmt, 1,
SQL_PARAM_INPUT, SQL_C_CHAR, info->sqlType, sizeof(fk_scoring_r_007ef)-1,
info->scale,  fk_scoring_r_007ef, sizeof(fk_scoring_r_007ef), NULL);
 if (ODBC_SUCCESSFUL(info->sqlca->rc))
info->sqlca->rc = TiodbcParameter(&hstmt_0118489145_1, 2,
    "", "SCORE_CARD", "FK_SCORING_RECOTIME0");
 if (ODBC_SUCCESSFUL(info->sqlca->rc))
info->sqlca->rc = SQLBindParameter(hstmt_0118489145_1.hstmt, 2,
SQL_PARAM_INPUT, SQL_C_TYPE_TIMESTAMP, info->sqlType, info->precision,
info->scale, &fk_scoring_r_011ef, sizeof(fk_scoring_r_011ef), NULL);
 if (ODBC_SUCCESSFUL(info->sqlca->rc))
info->sqlca->rc = TiodbcParameter(&hstmt_0118489145_1, 3,
    "", "SCORE_CARD", "FK_SCORING_RECODATE0");
 if (ODBC_SUCCESSFUL(info->sqlca->rc))
info->sqlca->rc = SQLBindParameter(hstmt_0118489145_1.hstmt, 3,
SQL_PARAM_INPUT, SQL_C_TYPE_DATE, info->sqlType, info->precision, info->scale,
&fk_scoring_r_015ef, sizeof(fk_scoring_r_015ef), NULL);
 if (ODBC_SUCCESSFUL(info->sqlca->rc))
hstmt_0118489145_1.pODBChstmt->reuse = TRUE;
}
 if (ODBC_SUCCESSFUL(info->sqlca->rc))
info->sqlca->rc = SQLExecute(hstmt_0118489145_1.hstmt);
 if (ODBC_NOT_SUCCESSFUL(info->sqlca->rc))
   f_118489145_odbc_dberror(&hstmt_0118489145_1);
 if (((ODBC_NOT_FOUND(info->sqlca->rc)) ||
    ((ODBC_SUCCESSFUL(info->sqlca->rc) &&
ODBC_SUCCESSFUL(SQLRowCount(hstmt_0118489145_1.hstmt, &odbcRowCount)) &&
odbcRowCount == 0))) ||
    ((ODBC_SUCCESSFUL(info->sqlca->rc) &&
ODBC_SUCCESSFUL((SQLRowCount(hstmt_0118489145_1.hstmt, &odbcRowCount))) &&
odbcRowCount == 1)))
{
info->sqlca->rc = TiodbcFreeStmt(&hstmt_0118489145_1);
 if (ODBC_NOT_SUCCESSFUL(info->sqlca->rc))
   f_118489145_odbc_dberror(&hstmt_0118489145_1);
}
 else {
f_118489145_odbc_dberror(&hstmt_0118489145_1);
}
}

static void f_118489145_odbc_dberror(TIHSTMT * tihstmt)
{
TiodbcError(tihstmt);
memcpy(globdata->psmgr_dasg_data.save_sqlca,
    info->sqlca,
    sizeof(* info->sqlca));
strcpy(globdata->psmgr_dasg_data.last_status, db_error);
f_118489145_error();
}


static void f_118489145_evaluate(void)
{
 if (relmm_cgvalue == 0L)
{
f_4085();
goto f_0118489145_evaluate_exit;
}
longjmp(excp_jumpbuf, TRACE_EXCEPTION);
f_0118489145_evaluate_exit: 
;
}


static void f_118489145_error(void)
{
strcpy(globdata->psmgr_dasg_data.status_flag, fatal_error);
 if (strcmp(dl_0118489145, succeeds) != 0)
strcpy(globdata->psmgr_dasg_data.last_status, dl_0118489145);
longjmp(excp_jumpbuf, FUNCTION_EXCEPTION);
}


/*  DISASSOC RELMM DOCMENTS */
static void f_4085(void)
{
globdata->v1present = 'Y';
globdata->v2present = 'N';
globdata->cascade1 = 'N';
globdata->cascade2 = 'Y';
globdata->processq_flag = 'N';
F0004888(ief_runtime_parm1,
    ief_runtime_parm2,
    globdata,
    pda_queue_cmcb,
    pscore_card_001dr,
    &scoring_reco_019dr);
 if (strcmp(globdata->psmgr_dasg_data.status_flag, "  ") != 0)
f_118489145_error();
}
